# Generated by Django 3.1.7 on 2021-04-04 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210404_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryinfo',
            old_name='Province',
            new_name='province',
        ),
    ]
