# Generated by Django 3.1.7 on 2021-04-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210404_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='mobile_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
