# Generated by Django 3.1.7 on 2021-04-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210406_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Order confirmed'), ('2', 'Picked by courier'), ('3', 'On the way'), ('4', 'Delivered'), ('5', 'Cancelled')], max_length=80, null=True),
        ),
    ]
