# Generated by Django 3.1.7 on 2021-04-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_customer_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sms_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
