# Generated by Django 3.1.7 on 2021-04-12 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210412_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscode',
            name='user',
        ),
        migrations.AddField(
            model_name='smscode',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
    ]
