# Generated by Django 3.1.7 on 2021-04-12 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210412_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscode',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.smscode'),
        ),
    ]
