# Generated by Django 3.1.7 on 2021-04-12 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20210412_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sms_code',
        ),
        migrations.AddField(
            model_name='smscode',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
