# Generated by Django 3.1.7 on 2021-04-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20210412_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smscode',
            old_name='user',
            new_name='customer',
        ),
    ]
