# Generated by Django 3.1.7 on 2021-04-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ph_locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='region',
        ),
        migrations.DeleteModel(
            name='Barangay',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
